export const REQUEST_INVENTORY_PENDING = 'REQUEST_INVENTORY_PENDING';
export const REQUEST_INVENTORY_SUCCESS = 'REQUEST_INVENTORY_SUCCESS';
export const REQUEST_INVENTORY_FAILED = 'REQUEST_INVENTORY_FAILED';
